### ISSUE TITLE
Albus\VariForm\

### ISSUE THREAD

**Issue by Titamik** [VershininSpace/cgsrf.ru#7]
Для плагина Albus\VariForm\ сделать описание и пр. висит непонятно что

**Comment by waynelogic** [comment]
Это я хотел свой плагин формы сделать - но потом решил его на своем проекте запилить. Та что я его ремувну отсюда)

**Comment by waynelogic** [comment]
Плагин удалил

**Comment by waynelogic** [comment]
Плагин удален. Будет разрабатываться отдельно от проекта, потом буду интегрировать сюда. В плагине будет встроенная поддержка oc-request.
